### PR TITLE
Fix eager scie-tote extraction.

### LINKED ISSUE #43: The scie-tote is always extracted.
As demonstrated with the 0.3.8 release using the example in [ptex](https://github.com/a-scie/ptex#how-ptex-works) which yields a scie of:
```
$ curl -sSL https://github.com/a-scie/jump/releases/download/v0.3.8/scie-jump-linux-x86_64 > example/scie-jump-linux-x86_64
$ rm skinny-scie && example/scie-jump-linux-x86_64 example/lift.json
example/lift.json: /home/jsirois/dev/a-scie/ptex/skinny-scie
$ zipinfo skinny-scie
Archive:  skinny-scie
Zip file size: 5729378 bytes, number of entries: 1
warning [skinny-scie]:  1459568 extra bytes at beginning or within zipfile
  (attempting to process anyway)
-rwxr-xr-x  4.6 unx  4268672 b- stor 80-Jan-01 00:00 ptex-linux-x86_64
1 file, 4268672 bytes uncompressed, 4268672 bytes compressed:  0.0%
```

1st run:
```
$ rm -rf ~/.nce && RUST_LOG=debug ./skinny-scie
[DEBUG TimerFinished] assemble(), Elapsed=1.97µs
[DEBUG TimerFinished] digest(), Elapsed=4.005µs
[DEBUG TimerFinished] load_scie(), Elapsed=72.826µs
[DEBUG TimerFinished] new(), Elapsed=1.781µs
[DEBUG TimerFinished] digest_reader(), Elapsed=6.302608ms
[DEBUG jump::installer] The zip destination /tmp/.tmpyGSDOa/scie-tote of size 4268804 had expected hash
[DEBUG TimerFinished] unpack_archive(), Elapsed=10.431485ms
[DEBUG TimerFinished] digest_reader(), Elapsed=6.356938ms
[DEBUG jump::installer] The blob destination /home/jsirois/.nce/85b1348e197f83cc6c0e607849dc8fa2ac96ffc0885d3f506edbe5d714670adc/ptex-linux-x86_64 of size 4268672 had expected hash
[DEBUG TimerFinished] unpack_blob(), Elapsed=8.304434ms
[INFO  jump::installer] Loading cpython-3.10.8+20221106-x86_64-unknown-linux-gnu-install_only.tar.gz via "/home/jsirois/.nce/85b1348e197f83cc6c0e607849dc8fa2ac96ffc0885d3f506edbe5d714670adc/ptex-linux-x86_64"...
Downloaded 27555856 of 27555856 bytes (100%) from https://github.com/indygreg/python-build-standalone/releases/download/20221106/cpython-3.10.8+20221106-x86_64-unknown-linux-gnu-install_only.tar.gz
[DEBUG TimerFinished] digest_reader(), Elapsed=45.468181ms
[DEBUG jump::installer] The tar.gz destination /home/jsirois/.nce/6c8db44ae0e18e320320bbaaafd2d69cde8bfea171ae2d651b7993d1396260b7/cpython-3.10.8+20221106-x86_64-unknown-linux-gnu-install_only.tar.gz of size 27555856 had expected hash
[DEBUG TimerFinished] unpack_tar(), Elapsed=237.829069ms
[DEBUG TimerFinished] unpack_archive(), Elapsed=5.597074065s
[DEBUG TimerFinished] install(), Elapsed=5.616264025s
[DEBUG TimerFinished] prepare_boot(), Elapsed=5.616678143s
Hello World!
```

Subsequent run with a warm cache:
```
$ RUST_LOG=debug ./skinny-scie
[DEBUG TimerFinished] assemble(), Elapsed=1.616µs
[DEBUG TimerFinished] digest(), Elapsed=3.423µs
[DEBUG TimerFinished] load_scie(), Elapsed=74.288µs
[DEBUG TimerFinished] new(), Elapsed=2.058µs
[DEBUG jump::atomic] The atomic file at /home/jsirois/.nce/066d340e05b4c1200817152a7ab9dbf2f0b0661925566cffcdf03887316646be/lift.json has already been established.
[DEBUG TimerFinished] digest_reader(), Elapsed=6.578561ms
[DEBUG jump::installer] The zip destination /tmp/.tmpaWJPLo/scie-tote of size 4268804 had expected hash
[DEBUG TimerFinished] unpack_archive(), Elapsed=8.538348ms
[DEBUG jump::atomic] The atomic file at /home/jsirois/.nce/85b1348e197f83cc6c0e607849dc8fa2ac96ffc0885d3f506edbe5d714670adc/ptex-linux-x86_64 has already been established.
[DEBUG TimerFinished] unpack_blob(), Elapsed=5.037µs
[DEBUG jump::atomic] The atomic directory at /home/jsirois/.nce/6c8db44ae0e18e320320bbaaafd2d69cde8bfea171ae2d651b7993d1396260b7/cpython-3.10.8+20221106-x86_64-unknown-linux-gnu-install_only.tar.gz has already been established.
[DEBUG TimerFinished] unpack_archive(), Elapsed=16.87µs
[DEBUG TimerFinished] install(), Elapsed=9.097267ms
[DEBUG TimerFinished] prepare_boot(), Elapsed=9.375412ms
Hello World!
```

Note that 8.538348ms is spent needlessly unpacking the scie-tote to `/tmp/.tmpaWJPLo/scie-tote` only to just after determine that the `ptex-linux-x86_64` contained within was already extracted to the `~/.nce`.

If no file is needed from the scie-tote, the scie-tote should never extract. The eager extraction happens here:
https://github.com/a-scie/jump/blob/69f70de2b0961567becbe7fed165aebe315bb3fd/jump/src/installer.rs#L233-L248

### PR DESCRIPTION
**Pull request by jsirois**
Previously a scie utilizing a scie-tote would extract that scie-tote on
every run whether or not the file entries of the scie-tote had already
been extracted themselves. Fix this and add a ptex example which is
where this issue was 1st discovered.

Fixes #43

### CODE REVIEW

**Comment by jsirois** [comment]
I'm still not really sure what to do with the review protocol for the science projects. Both of your feedback has been useful; so I'm continuing to add you as reviewers to significant changes. If you'd rather I not, let me know and I can plow ahead.

**Comment by sureshjoshi** [comment]
I'm perfectly fine being added - as I'm interested in this project, and trying to make updates to the Pants plugin, but I'd like to not be a bottleneck if you're waiting on reviews.

I'm also useless on Rust-heavy commits, but I'm always happy to ask the "stupid" questions for the benefit of the community.

**Comment by sureshjoshi** [comment]
Clarity on the bug:

> whether or not the file entries of the scie-tote had already been extracted themselves

Is the extraction location here the `~/.nce` or a tempdir?

**Comment by jsirois** [comment]
The scie tote gets extracted to a temp dir. This is needed (only when files inside it are needed) because the scie tote is a zip and extracting from a zip stream requires random access (unlike tar).

File: jump/src/installer.rs [hunk 1]
```diff
@@ -231,22 +232,33 @@ pub(crate) fn install(files: &[FileEntry], payload: &[u8]) -> Result<(), String>
...
-                    || Ok((Cursor::new(bytes), ())),
-                    tote_file.hash.as_str(),
-                    &scie_tote_path,
-                )?;
+                let mut scie_tote: Option<TempDir> = None;
+                let mut scie_tote_src = || {
+                    if let Some(tempdir) = scie_tote.as_ref() {
+                        return Ok::<_, String>(tempdir.path().join(&tote_file.name));
+                    }
+                    let scie_tote_tmpdir = TempDir::new().map_err(|e| {
```
Comment (jsirois) [inline jump/src/installer.rs:240]: Here's the scie tote extraction. To a temp dir, just like before, but this time lazily in a closure that uses an Option to hold a single extraction.

Comment (sureshjoshi) [reply jump/src/installer.rs:240]: Yep, okay, that's what I thought - just wanted to confirm my understanding about the eager extraction bug.

**Review by sureshjoshi — APPROVED** [review]
